---

- ansible.builtin.include_role: # config bashrc
    name: alex.debian13.configbash

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - curl
    - jq
    - pip
    - expect
    - git
    - cifs-utils
    - nmap
    - xorriso
    - libssl3
    - dnsutils
    - apt-transport-https
    - curl
    - wget
    # - net-utils
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install a list of python packages
  ansible.builtin.pip:
    name: "{{ packages }}"
    state: present
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1
  vars:
    packages:
    - pyyaml
    - docker
    - 'fastapi[all]'
    - 'pymongo[srv]'
    - python-dotenv
    - requests_toolbelt
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

# - name: Ensure alex folder exists
#   file:
#     path: "/home/alex/.alex"
#     state: directory
#     owner: root
#     group: root
#     mode: 0777
#   vars:
#     ansible_connection: "{{ prop_ansible_connection }}"
#     ansible_host: "{{ prop_ipaddress }}"
#   become: true

# - name: Ensure alex folder exists
#   file:
#     path: "/root/.alex"
#     state: directory
#     owner: root
#     group: root
#     mode: 0777
#   vars:
#     ansible_connection: "{{ prop_ansible_connection }}"
#     ansible_host: "{{ prop_ipaddress }}"
#   become: true

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: .smbcred.j2
    dest: "/home/{{ prop_admin_username }}/.{{ prop_basename }}/.smbcred"
    owner: "{{ prop_admin_username }}"
    group: "{{ prop_admin_groupname }}"
    mode: '0400'
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Mount SMB volume
  ansible.posix.mount:
    src: "{{ item.source }}"
    path: "{{ item.path }}"
    opts: 'rw,auto,vers=3,file_mode=0777,dir_mode=0777,dom=WORKGROUP,credentials=/home/{{ prop_admin_username }}/.{{ prop_basename }}/.smbcred'
    fstype: cifs
    state: mounted
  loop: "{{ prop_smb_mounts }}"
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: ensure all mounts are mounted
  shell: |
    mount -a
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install Github CLI
  apt:
    deb: /mnt/sources-dev/deb/gh/gh_2.48.0_linux_amd64.deb
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install Proxmox Auto Install Assistant
  apt:
    deb: /mnt/sources-dev/deb/proxmox/proxmox-auto-install-assistant_8.4.6_amd64.deb
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- ansible.builtin.include_role:
    name: alex.debian13.installoras

- ansible.builtin.include_role:
    name: alex.debian13.certificates

 