---

- name: Create mount points
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  loop: "{{ prop_os.nfs_mounts | default([]) }}"
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_host.ipaddress }}"
  become: true

- name: Mount NFS volume
  ansible.posix.mount:
    src: "{{ item.source }}"
    path: "{{ item.path }}"
    opts: '_netdev,rw,nofail'
    fstype: nfs
    state: mounted
  loop: "{{ prop_os.nfs_mounts | default([]) }}"
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_host.ipaddress }}"
  become: true
