---

- ansible.builtin.include_role: # knownoshost
    name: alex.base.knownoshost

- name: Upload files
  ansible.builtin.template:
    src: "{{ item.source }}"
    dest: "{{ item.target }}"
    owner: "{{ prop_admin_username }}"
    group: "{{ prop_admin_groupname }}"
    mode: '0777'
  loop:
    - source: config.debian.sh.j2
      target: "/{{ prop_basename }}/nginx/html/config.debian.sh"
  vars:
    ansible_connection: "{{ prop_ansible_connection }}"
    ansible_host: "{{ prop_ipaddress }}"
  become: true




