---

- ansible.builtin.include_role: # aptupgrade
    name: alex.debian13.aptupgrade

- ansible.builtin.include_role: # smbshares
    name: alex.debian13.smbshares

- ansible.builtin.include_role: # mount smb shares
    name: alex.debian13.mountsmbshares

- ansible.builtin.include_role: # datafolders
    name: alex.debian13.datafolders

- ansible.builtin.include_role: # certificates
    name: alex.debian13.certificates

- ansible.builtin.include_role: # cronjobs
    name: alex.debian13.cronjobs

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ prop_hostname }}"
  register: hostnameresult
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Conditionally reboot the machine with all defaults
  reboot:
  when: hostnameresult.changed
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true


