---

- name: Create local datafolders
  file:
    path: "/{{ prop_basename }}/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  loop: "{{ args_datafolder_local | default([]) }}"
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Create remote datafolders
  file:
    path: "/mnt/{{ item.mount }}/{{ item.service }}/{{ prop_hostname }}/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  loop: "{{ args_datafolder_remote | default([]) }}"
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true
