---

- name: "Playbook: Build Debian 13 Base Template"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.debian13.buildbasetemplate
